version: '3.6'
# FYI: start_period works only for version >= 3.4
services:
  postgres:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: user_svc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/01_initdb.sql

  kafka:
    image: bitnami/kafka:2.8.0
    hostname: localhost
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HEAP_OPTS: -Xmx256m -Xms256m
      LOG4J_LOGGER_KAFKA: ERROR
      LOG4J_LOGGER_ORG_APACHE_KAFKA: ERROR
      LOG4J_LOGGER_ORG_I0ITEC_ZKCLIENT_ZKCLIENT: ERROR
      LOG4J_LOGGER_ORG_APACHE_ZOOKEEPER: ERROR
      LOG4J_ROOTLOGGER: "ERROR,stdout,kafkaAppender"
      JVMFLAGS: "-XX:ActiveProcessorCount=1"
    ports:
      - "9092:9092"
    healthcheck:
      test: "zookeeper-shell.sh $$KAFKA_ZOOKEEPER_CONNECT ls /brokers/ids | tail -1 | grep -v '\\[\\]'"
      interval: 10s
      timeout: 10s
      retries: 10

  zookeeper:
    image: bitnami/zookeeper:3.5.6
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_LOG4J_PROP: "ERROR,ROLLINGFILE"
      ZOO_HEAP_SIZE: 256
      ALLOW_ANONYMOUS_LOGIN: "yes"
      JVMFLAGS: "-XX:ActiveProcessorCount=1"
    healthcheck:
      test: "/opt/bitnami/zookeeper/bin/zkServer.sh status"
      interval: 10s
      timeout: 10s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:1.21
    hostname: jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    healthcheck:
      test: wget -O - http://127.0.0.1:16686/
      interval: 10s
      timeout: 10s
      retries: 10

  everything:
    image: zablvit/zero@sha256:7037ea9215d458532f7ea171c7b65eea7e2c7659f3b0667c70fa48a13ad69a1f
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy